"""Revert to simple provider-service limit architecture

Revision ID: 3602705e29dc
Revises: 
Create Date: 2025-08-06 18:43:16.469957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3602705e29dc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone_numbers', 'limit_profile_id')
    op.add_column('providers', sa.Column('daily_limit', sa.Integer(), nullable=True))
    op.add_column('services', sa.Column('daily_limit', sa.Integer(), nullable=True))
    op.drop_column('services', 'keywords')
    op.drop_column('services', 'default_daily_limit')
    op.drop_column('services', 'allowed_senders')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('allowed_senders', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('services', sa.Column('default_daily_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('services', sa.Column('keywords', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('services', 'daily_limit')
    op.drop_column('providers', 'daily_limit')
    op.add_column('phone_numbers', sa.Column('limit_profile_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
