"""consolidate_performance_indexes_into_models

Revision ID: 3a515f2b79db
Revises: 48aabd94aad0
Create Date: 2025-08-30 21:15:50.362846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a515f2b79db'
down_revision: Union[str, Sequence[str], None] = '48aabd94aad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phone_numbers_lookup_perf'), table_name='phone_numbers')
    op.drop_index(op.f('idx_sessions_status_created_at'), table_name='sessions')
    op.drop_index(op.f('idx_sms_session_received'), table_name='sms_messages')
    op.create_index('idx_sms_session_received', 'sms_messages', ['session_id', 'received_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sms_session_received', table_name='sms_messages')
    op.create_index(op.f('idx_sms_session_received'), 'sms_messages', ['session_id', sa.literal_column('received_at DESC')], unique=False)
    op.create_index(op.f('idx_sessions_status_created_at'), 'sessions', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_phone_numbers_lookup_perf'), 'phone_numbers', ['country_id', 'provider_id', 'is_in_use', 'is_active', 'operator_id', 'sort_order'], unique=False)
    # ### end Alembic commands ###
