"""add_performance_indexes_to_phone_numbers

Revision ID: 48aabd94aad0
Revises: 8661584e3cb2
Create Date: 2025-08-30 20:59:21.995143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48aabd94aad0'
down_revision: Union[str, Sequence[str], None] = '8661584e3cb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_phone_numbers_lookup_perf', 'phone_numbers', ['country_id', 'provider_id', 'is_in_use', 'is_active', 'operator_id', 'sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_phone_numbers_lookup_perf', table_name='phone_numbers')
    # ### end Alembic commands ###
