"""add ServiceProviderCountryLimit table

Revision ID: 5734e84af7bd
Revises: 3602705e29dc
Create Date: 2025-08-06 23:04:00.050551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5734e84af7bd'
down_revision: Union[str, Sequence[str], None] = '3602705e29dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_provider_country_limit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_provider_country_limit_country_id'), 'service_provider_country_limit', ['country_id'], unique=False)
    op.create_index(op.f('ix_service_provider_country_limit_provider_id'), 'service_provider_country_limit', ['provider_id'], unique=False)
    op.create_index(op.f('ix_service_provider_country_limit_service_id'), 'service_provider_country_limit', ['service_id'], unique=False)
    op.create_index('ix_svc_prv_ctr_limit', 'service_provider_country_limit', ['service_id', 'provider_id', 'country_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_svc_prv_ctr_limit', table_name='service_provider_country_limit')
    op.drop_index(op.f('ix_service_provider_country_limit_service_id'), table_name='service_provider_country_limit')
    op.drop_index(op.f('ix_service_provider_country_limit_provider_id'), table_name='service_provider_country_limit')
    op.drop_index(op.f('ix_service_provider_country_limit_country_id'), table_name='service_provider_country_limit')
    op.drop_table('service_provider_country_limit')
    # ### end Alembic commands ###
