"""Add ServiceLimit table

Revision ID: 60d88e50cfd1
Revises: 5734e84af7bd
Create Date: 2025-08-06 23:40:25.369129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d88e50cfd1'
down_revision: Union[str, Sequence[str], None] = '5734e84af7bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_limits_country_id'), 'service_limits', ['country_id'], unique=False)
    op.create_index(op.f('ix_service_limits_is_active'), 'service_limits', ['is_active'], unique=False)
    op.create_index(op.f('ix_service_limits_provider_id'), 'service_limits', ['provider_id'], unique=False)
    op.create_index(op.f('ix_service_limits_service_id'), 'service_limits', ['service_id'], unique=False)
    op.create_index('unique_service_provider_country', 'service_limits', ['service_id', 'provider_id', 'country_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_service_provider_country', table_name='service_limits')
    op.drop_index(op.f('ix_service_limits_service_id'), table_name='service_limits')
    op.drop_index(op.f('ix_service_limits_provider_id'), table_name='service_limits')
    op.drop_index(op.f('ix_service_limits_is_active'), table_name='service_limits')
    op.drop_index(op.f('ix_service_limits_country_id'), table_name='service_limits')
    op.drop_table('service_limits')
    # ### end Alembic commands ###
