"""add orphan_sms

Revision ID: 60dcb8844e48
Revises: 087f474f6149
Create Date: 2025-08-08 12:18:12.325632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60dcb8844e48'
down_revision: Union[str, Sequence[str], None] = '087f474f6149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orphan_sms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number_str', sa.String(), nullable=False),
    sa.Column('source_addr', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orphan_sms_country_id'), 'orphan_sms', ['country_id'], unique=False)
    op.create_index(op.f('ix_orphan_sms_operator_id'), 'orphan_sms', ['operator_id'], unique=False)
    op.create_index(op.f('ix_orphan_sms_phone_number_str'), 'orphan_sms', ['phone_number_str'], unique=False)
    op.create_index(op.f('ix_orphan_sms_provider_id'), 'orphan_sms', ['provider_id'], unique=False)
    op.create_index(op.f('ix_orphan_sms_received_at'), 'orphan_sms', ['received_at'], unique=False)
    op.create_index(op.f('ix_orphan_sms_source_addr'), 'orphan_sms', ['source_addr'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orphan_sms_source_addr'), table_name='orphan_sms')
    op.drop_index(op.f('ix_orphan_sms_received_at'), table_name='orphan_sms')
    op.drop_index(op.f('ix_orphan_sms_provider_id'), table_name='orphan_sms')
    op.drop_index(op.f('ix_orphan_sms_phone_number_str'), table_name='orphan_sms')
    op.drop_index(op.f('ix_orphan_sms_operator_id'), table_name='orphan_sms')
    op.drop_index(op.f('ix_orphan_sms_country_id'), table_name='orphan_sms')
    op.drop_table('orphan_sms')
    # ### end Alembic commands ###
