"""initial_full_schema

Revision ID: 733224c7a544
Revises: 
Create Date: 2025-07-31 16:31:20.546821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '733224c7a544'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key'), 'api_keys', ['key'], unique=True)
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('iso_code', sa.String(length=10), nullable=False),
    sa.Column('phone_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_iso_code'), 'countries', ['iso_code'], unique=True)
    op.create_index(op.f('ix_countries_phone_code'), 'countries', ['phone_code'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('smpp_host', sa.String(), nullable=False),
    sa.Column('smpp_port', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_name'), 'providers', ['name'], unique=True)
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_services_code'), 'services', ['code'], unique=True)
    op.create_table('allowed_senders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'service_id', name='uq_sender_service')
    )
    op.create_index(op.f('ix_allowed_senders_name'), 'allowed_senders', ['name'], unique=False)
    op.create_table('operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operators_name'), 'operators', ['name'], unique=False)
    op.create_table('phone_numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number_str', sa.String(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_in_use', sa.Boolean(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_numbers_is_in_use'), 'phone_numbers', ['is_in_use'], unique=False)
    op.create_index(op.f('ix_phone_numbers_number_str'), 'phone_numbers', ['number_str'], unique=True)
    op.create_index(op.f('ix_phone_numbers_sort_order'), 'phone_numbers', ['sort_order'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number_str', sa.String(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('phone_number_id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phone_number_id'], ['phone_numbers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_phone_number_str'), 'sessions', ['phone_number_str'], unique=False)
    op.create_index(op.f('ix_sessions_status'), 'sessions', ['status'], unique=False)
    op.create_table('sms_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('source_addr', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sms_code', 'sms_messages', ['code'], unique=False)
    op.create_index(op.f('ix_sms_messages_source_addr'), 'sms_messages', ['source_addr'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sms_messages_source_addr'), table_name='sms_messages')
    op.drop_index('ix_sms_code', table_name='sms_messages')
    op.drop_table('sms_messages')
    op.drop_index(op.f('ix_sessions_status'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_phone_number_str'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_phone_numbers_sort_order'), table_name='phone_numbers')
    op.drop_index(op.f('ix_phone_numbers_number_str'), table_name='phone_numbers')
    op.drop_index(op.f('ix_phone_numbers_is_in_use'), table_name='phone_numbers')
    op.drop_table('phone_numbers')
    op.drop_index(op.f('ix_operators_name'), table_name='operators')
    op.drop_table('operators')
    op.drop_index(op.f('ix_allowed_senders_name'), table_name='allowed_senders')
    op.drop_table('allowed_senders')
    op.drop_index(op.f('ix_services_code'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_providers_name'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_countries_phone_code'), table_name='countries')
    op.drop_index(op.f('ix_countries_iso_code'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_api_keys_key'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
