"""Add system_type to Provider

Revision ID: 79efc6f6d3c8
Revises: 60dcb8844e48
Create Date: 2025-08-13 09:59:25.803177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79efc6f6d3c8'
down_revision: Union[str, Sequence[str], None] = '60dcb8844e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phone_numbers_provider_country'), table_name='phone_numbers')
    op.add_column('providers', sa.Column('system_type', sa.String(length=50), nullable=True))
    op.drop_index(op.f('ix_sessions_status_created_at'), table_name='sessions')
    op.drop_index(op.f('ix_sms_messages_received_at'), table_name='sms_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_sms_messages_received_at'), 'sms_messages', ['received_at'], unique=False)
    op.create_index(op.f('ix_sessions_status_created_at'), 'sessions', ['status', 'created_at'], unique=False)
    op.drop_column('providers', 'system_type')
    op.create_index(op.f('ix_phone_numbers_provider_country'), 'phone_numbers', ['provider_id', 'country_id'], unique=False)
    # ### end Alembic commands ###
