"""Add connection_type to Provider model

Revision ID: c0fc2b040680
Revises: 79efc6f6d3c8
Create Date: 2025-08-13 12:18:00.847054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0fc2b040680'
down_revision: Union[str, Sequence[str], None] = '79efc6f6d3c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('connection_type', sa.String(length=10), server_default='outbound', nullable=False))
    op.create_index(op.f('ix_providers_connection_type'), 'providers', ['connection_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_providers_connection_type'), table_name='providers')
    op.drop_column('providers', 'connection_type')
    # ### end Alembic commands ###
