"""Add indexes to PhoneNumber

Revision ID: efde51d8c034
Revises: 0b85be47dc74
Create Date: 2025-08-13 22:20:38.230849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efde51d8c034'
down_revision: Union[str, Sequence[str], None] = '0b85be47dc74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_phone_numbers_country_id'), 'phone_numbers', ['country_id'], unique=False)
    op.create_index(op.f('ix_phone_numbers_operator_id'), 'phone_numbers', ['operator_id'], unique=False)
    op.create_index(op.f('ix_phone_numbers_provider_id'), 'phone_numbers', ['provider_id'], unique=False)
    op.create_index('ix_session_cleanup', 'sessions', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_sessions_api_key_id'), 'sessions', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_sessions_phone_number_id'), 'sessions', ['phone_number_id'], unique=False)
    op.create_index(op.f('ix_sessions_service_id'), 'sessions', ['service_id'], unique=False)
    op.create_index(op.f('ix_sms_messages_code'), 'sms_messages', ['code'], unique=False)
    op.create_index(op.f('ix_sms_messages_received_at'), 'sms_messages', ['received_at'], unique=False)
    op.create_index(op.f('ix_sms_messages_session_id'), 'sms_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sms_messages_session_id'), table_name='sms_messages')
    op.drop_index(op.f('ix_sms_messages_received_at'), table_name='sms_messages')
    op.drop_index(op.f('ix_sms_messages_code'), table_name='sms_messages')
    op.drop_index(op.f('ix_sessions_service_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_phone_number_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_api_key_id'), table_name='sessions')
    op.drop_index('ix_session_cleanup', table_name='sessions')
    op.drop_index(op.f('ix_phone_numbers_provider_id'), table_name='phone_numbers')
    op.drop_index(op.f('ix_phone_numbers_operator_id'), table_name='phone_numbers')
    op.drop_index(op.f('ix_phone_numbers_country_id'), table_name='phone_numbers')
    # ### end Alembic commands ###
